class CfgPatches
{
	class BHA_Acolytes
	{
		units[]=
		{
			"BHA_Acolytes_Acolyte",
			"BHA_Acolytes_Farseer",
			"BHA_Acolytes_Wayfarer",
			"BHA_Acolytes_Oracle",
			"BHA_Acolytes_Pacifier",
			"BHA_Acolytes_Mender",
			"BHA_Acolytes_Annihilator",
			"BHA_Acolytes_Obliterator",
			"BHA_Acolytes_Bishop",
			"BHA_Acolytes_HonorGuard",
			"BHA_Acolytes_HonorGuardLeader",
			"BHA_Acolytes_HonorGuard_Immortal",
			"BHA_Acolytes_HonorGuard_Pacifier"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class I_Soldier_base_F;
	class BHA_Acolytes_Base: I_Soldier_base_F
	{
		side=2;
		scope=0;
		scopeCurator=0;
		faction="BHA_Units";
		editorSubCategory="BHA_Acolytes";
		uniformClass="SC_Undersuit_Black";
		backpack="MET_MDFBackpack_Black";
		genericNames="RussianMen";
		identityTypes[]=
		{
			"LanguageRUS_F",
			"Head_Euro",
			"G_NATO_default"
		};
		Weapons[]=
		{
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		Items[]=
		{
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"ACE_CableTie",
			"ACE_CableTie",
			"ACE_CableTie",
			"LFP_Skirata_Knife"
		};
		respawnItems[]=
		{
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"ACE_CableTie",
			"ACE_CableTie",
			"ACE_CableTie",
			"LFP_Skirata_Knife"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"G_Bandanna_blk",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"G_Bandanna_blk",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black"
		};
		/*class Attributes
		{
			// VCOM compatibility: set skill to max via VCOM attributes if present
			VCOM_AISkill = 0.8;
		};*/
		class EventHandlers
		{
			init = "_unit = _this select 0; if (local _unit) then { {_unit setSkill [_x, 0.8]; } forEach ['aimingAccuracy','aimingShake','aimingSpeed','commanding','courage','general','reloadSpeed','spotDistance','spotTime']; if !(isNil 'VCOM_AI_SetSkill') then { [_unit, 0.8] call VCOM_AI_SetSkill; }; };";
		};
	};
	class BHA_HonorGuard_Base: I_Soldier_base_F
	{
		side=2;
		scope=0;
		scopeCurator=0;
		faction="BHA_Units";
		editorSubCategory="BHA_HG";
		uniformClass="SC_Undersuit_Black";
		backpack="MET_MDFBackpack_SSD";
		genericNames="RussianMen";
		identityTypes[]=
		{
			"LanguageRUS_F",
			"Head_Euro",
			"G_NATO_default"
		};
		Weapons[]=
		{
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Arkanian_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		Items[]=
		{
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"ACE_CableTie",
			"ACE_CableTie",
			"ACE_CableTie",
			"LFP_Skirata_Knife"
		};
		respawnItems[]=
		{
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"ACE_CableTie",
			"ACE_CableTie",
			"ACE_CableTie",
			"LFP_Skirata_Knife"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"G_Bandanna_blk",
			"MET_MDF_Helmet_PHOBOS",
			"MET_MDF_Heavy_PHOBOS"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"G_Bandanna_blk",
			"MET_MDF_Helmet_PHOBOS",
			"MET_MDF_Heavy_PHOBOS"
		};
		class Attributes
		{
			// VCOM compatibility: set skill to max via VCOM attributes if present
			VCOM_AISkill = 1;
		};
		class EventHandlers
		{
			init = "_unit = _this select 0; if (local _unit) then { {_unit setSkill [_x, 1]; } forEach ['aimingAccuracy','aimingShake','aimingSpeed','commanding','courage','general','reloadSpeed','spotDistance','spotTime']; if !(isNil 'VCOM_AI_SetSkill') then { [_unit, 1] call VCOM_AI_SetSkill; }; };";
		};
	};
	class BHA_Acolytes_Acolyte: BHA_Acolytes_Base
	{
		displayName="Acolyte";
		scope=2;
		scopeCurator=2;
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Acolyte.jpg";
		Weapons[]=
		{
			"MET_DLA13_C",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13_C",
			"Put",
			"Throw"
		};
	};
	class BHA_Acolytes_Farseer: BHA_Acolytes_Base
	{
		displayName="Acolyte Farseer";
		scope=2;
		scopeCurator=2;
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Farseer.jpg";
		Weapons[]=
		{
			"MET_DLA13",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13",
			"Put",
			"Throw"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFRecon"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFRecon"
		};
	};
	class BHA_Acolytes_Wayfarer: BHA_Acolytes_Base
	{
		displayName="Acolyte Wayfarer";
		scope=2;
		scopeCurator=2;
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Wayfarer.jpg";
		Weapons[]=
		{
			"MET_DLA13_ugl",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13_ugl",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_light_proton_mag",
			"MET_light_proton_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_light_proton_mag",
			"MET_light_proton_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFGrenadier"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFGrenadier"
		};
	};
	class BHA_Acolytes_Oracle: BHA_Acolytes_Base
	{
		displayName="Acolyte Oracle";
		scope=2;
		scopeCurator=2;
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Oracle.jpg";
		Weapons[]=
		{
			"MET_X300_Sniper",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_X300_Sniper",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFRecon"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFRecon"
		};
	};
	class BHA_Acolytes_Pacifier: BHA_Acolytes_Base
	{
		displayName="Acolyte Pacifier";
		scope=2;
		scopeCurator=2;
		icon="iconManMG";
		backpack="MET_MDFMGBackpack_Black";
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Pacifier.jpg";
		Weapons[]=
		{
			"MET_EL34",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_EL34",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_EL34_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_EL34_mag",
			"MET_EL34_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFmgkit"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ItemWatch",
			"MET_MDF_Helmet_Black",
			"MET_MDF_Heavy_Black",
			"SC_MDFmgkit"
		};
	};
	class BHA_Acolytes_Mender: BHA_Acolytes_Base
	{
		displayName="Acolyte Mender";
		scope=2;
		scopeCurator=2;
		icon="iconManMedic";
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Mender.jpg";
		backpack="MET_MDFMedicBackpack_Black";
		Weapons[]=
		{
			"MET_DLA13_C",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13_C",
			"Put",
			"Throw"
		};
	};
	class BHA_Acolytes_Annihilator: BHA_Acolytes_Base
	{
		displayName="Acolyte Annihilator";
		scope=2;
		scopeCurator=2;
		icon="iconManAT";
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Annihilator.jpg";
		backpack="MET_MDFATBackpack_Black";
		Weapons[]=
		{
			"MET_DLA13_C",
			"MET_HH12_SMRT",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13_C",
			"MET_HH12_SMRT",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
	class BHA_Acolytes_Obliterator: BHA_Acolytes_Base
	{
		displayName="Acolyte Obliterator";
		scope=2;
		scopeCurator=2;
		icon="iconManAT";
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Obliterator.jpg";
		backpack="MET_MDFAABackpack_Black";
		Weapons[]=
		{
			"MET_DLA13_C",
			"MET_HH12_SMRT",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_DLA13_C",
			"MET_HH12_SMRT",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"BHA_AA_SINGLE",
			"BHA_AA_SINGLE",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"MET_DLA13_mag",
			"BHA_AA_SINGLE",
			"BHA_AA_SINGLE",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
	class BHA_Acolytes_Bishop: BHA_Acolytes_Base
	{
		displayName="Acolyte Bishop";
		scope=2;
		scopeCurator=2;
		icon="iconManLeader";
		//editorpreview="\HDC_Units_mod\data\Editor Previews\BHA\Acolytes\BHA_Acolytes_Bishop.jpg";
		Weapons[]=
		{
			"MET_T20_rifle",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_T20_rifle",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
	class BHA_Acolytes_HonorGuard: BHA_HonorGuard_Base
	{
		displayName="Honor Guard";
		scope=2;
		scopeCurator=2;
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Apostles\BHA_Apostles_Apostle.jpg";
		Weapons[]=
		{
			"MET_Arkanian_Stock_F",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_Arkanian_Stock_F",
			"Put",
			"Throw"
		};
	};
	class BHA_Acolytes_HonorGuardLeader: BHA_HonorGuard_Base
	{
		displayName="Honor Guard Honorable";
		scope=2;
		scopeCurator=2;
		icon="iconManLeader";
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Apostles\BHA_Apostles_Apostle.jpg";
		Weapons[]=
		{
			"MET_Arkanian_Stock_F",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_Arkanian_Stock_F",
			"Put",
			"Throw"
		};
	};
	class BHA_Acolytes_HonorGuard_Immortal: BHA_HonorGuard_Base
	{
		displayName="Honor Guard Immortal";
		scope=2;
		scopeCurator=2;
		//icon="iconManLeader";
		backpack="MET_MDFBackpack_SSD_MG";
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Apostles\BHA_Apostles_Apostle.jpg";
		Weapons[]=
		{
			"met_FHR1",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"met_FHR1",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AA_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"MET_FHR1_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
	class BHA_Acolytes_HonorGuard_Pacifier: BHA_HonorGuard_Base
	{
		displayName="Honor Guard Pacifier";
		scope=2;
		scopeCurator=2;
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Apostles\BHA_Apostles_Apostle.jpg";
		Weapons[]=
		{
			"MET_BHA_SBB3",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_BHA_SBB3",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AA_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"MET_SBB3_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
};
class CfgGroups
{
	class INDEP
	{
		class BHA_Groups
		{
			name="[16th] Barysaw Holdings Authority";
			class BHA_Acolytes_inf_Groups
			{
				name="Acolyte Infantry Groups";
				class BHA_Acolytes_Squad
				{
					name="Squad";
					scope=2;
					side=2;
					faction="BHA_Units";
					icon="\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Unit0
					{
						side=2;
						vehicle="BHA_Acolytes_Bishop";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=2;
						vehicle="BHA_Acolytes_Farseer";
						rank="PRIVATE";
						position[]={1,-2,0};
					};
					class Unit2
					{
						side=2;
						vehicle="BHA_Acolytes_Wayfarer";
						rank="CORPORAL";
						position[]={-1,-2,0};
					};
					class Unit3
					{
						side=2;
						vehicle="BHA_Acolytes_Oracle";
						rank="CORPORAL";
						position[]={1,-3,0};
					};
					class Unit4
					{
						side=2;
						vehicle="BHA_Acolytes_Pacifier";
						rank="CORPORAL";
						position[]={-1,-3,0};
					};
					class Unit5
					{
						side=2;
						vehicle="BHA_Acolytes_Mender";
						rank="CORPORAL";
						position[]={1,-4,0};
					};
					class Unit6
					{
						side=2;
						vehicle="BHA_Acolytes_Annihilator";
						rank="CORPORAL";
						position[]={-1,-4,0};
					};
					class Unit7
					{
						side=2;
						vehicle="BHA_Acolytes_Obliterator";
						rank="CORPORAL";
						position[]={1,-5,0};
					};
					class Unit8
					{
						side=2;
						vehicle="BHA_Acolytes_Acolyte";
						rank="CORPORAL";
						position[]={-1,-5,0};
					};
				};
			};
			class BHA_Acolytes_hg_Groups
			{
				name="Acolyte Honor Guard Groups";
				class BHA_HG_Squad
				{
					name="Team";
					scope=2;
					side=2;
					faction="BHA_Units";
					icon="\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Unit0
					{
						side=2;
						vehicle="BHA_Acolytes_HonorGuardLeader";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=2;
						vehicle="BHA_Acolytes_HonorGuard";
						rank="PRIVATE";
						position[]={1,-2,0};
					};
					class Unit2
					{
						side=2;
						vehicle="BHA_Acolytes_HonorGuard";
						rank="CORPORAL";
						position[]={-1,-2,0};
					};
					class Unit3
					{
						side=2;
						vehicle="BHA_Acolytes_HonorGuard";
						rank="CORPORAL";
						position[]={1,-3,0};
					};
					class Unit4
					{
						side=2;
						vehicle="BHA_Acolytes_HonorGuard_Immortal";
						rank="CORPORAL";
						position[]={-1,-3,0};
					};
					class Unit5
					{
						side=2;
						vehicle="BHA_Acolytes_HonorGuard_Immortal";
						rank="CORPORAL";
						position[]={1,-4,0};
					};
					class Unit6
					{
						side=2;
						vehicle="BHA_Acolytes_HonorGuard_Pacifier";
						rank="CORPORAL";
						position[]={-1,-4,0};
					};
					class Unit7
					{
						side=2;
						vehicle="BHA_Acolytes_HonorGuard_Pacifier";
						rank="CORPORAL";
						position[]={1,-5,0};
					};
					class Unit8
					{
						side=2;
						vehicle="BHA_Acolytes_HonorGuard_Pacifier";
						rank="CORPORAL";
						position[]={-1,-5,0};
					};
				};
			};
		};
	};
};
class cfgMods
{
	author="";
	timepacked="1664364859";
};
