class CfgPatches
{
	class BHA_Apostles
	{
		units[]=
		{
			"BHA_Apostles_Apostle",
			"BHA_Apostles_Ascended",
			"BHA_Apostles_Immortal",
			"BHA_Apostles_Diviner",
			"BHA_Apostles_Decimator",
			"BHA_Apostles_Archbishop",
			"BHA_Apostles_Annihilator"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class I_Soldier_base_F;
	class BHA_Apostles_Base: I_Soldier_base_F
	{
		side=2;
		scope=0;
		scopeCurator=0;
		faction="BHA_Units";
		editorSubCategory="BHA_Apostles";
		uniformClass="SC_Undersuit_Black";
		backpack="MET_SentinelPack_Night_Black";
		genericNames="RussianMen";
		identityTypes[]=
		{
			"LanguageRUS_F",
			"Head_Euro",
			"G_NATO_default"
		};
		Weapons[]=
		{
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		Items[]=
		{
			"ACE_Canteen",
			"ACE_MRE_LambCurry",
			"ACE_Flashlight_KSF1",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"ACE_splint",
			"ACE_splint",
			"Weap_melee_knife"
		};
		respawnItems[]=
		{
			"ACE_Canteen",
			"ACE_MRE_LambCurry",
			"ACE_Flashlight_KSF1",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"LFP_item_bacta_bandage",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"ACE_splint",
			"ACE_splint",
			"Weap_melee_knife"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ACE_Altimeter",
			"G_Bandanna_blk",
			"MET_Helmet_SEN_SL_Black",
			"MET_Vest_SEN_Heavy_Black"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemGPS",
			"ItemCompass",
			"ItemRadio",
			"ACE_Altimeter",
			"G_Bandanna_blk",
			"MET_Helmet_SEN_SL_Black",
			"MET_Vest_SEN_Heavy_Black"
		};
		/*class Attributes
		{
			// VCOM compatibility: set skill to max via VCOM attributes if present
			VCOM_AISkill = 0.95;
		};*/
		class EventHandlers
		{
			init = "_unit = _this select 0; if (local _unit) then { {_unit setSkill [_x, 0.95]; } forEach ['aimingAccuracy','aimingShake','aimingSpeed','commanding','courage','general','reloadSpeed','spotDistance','spotTime']; if !(isNil 'VCOM_AI_SetSkill') then { [_unit, 0.95] call VCOM_AI_SetSkill; }; };";
		};
	};
	class BHA_Apostles_Apostle: BHA_Apostles_Base
	{
		displayName="Apostle";
		scope=2;
		scopeCurator=2;
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Apostles\BHA_Apostles_Apostle.jpg";
		Weapons[]=
		{
			"MET_T20_rifle",
			"MET_D200",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_T20_rifle",
			"MET_D200",
			"Put",
			"Throw"
		};
	};
	class BHA_Apostles_Ascended: BHA_Apostles_Base
	{
		displayName="Apostle Ascended";
		scope=2;
		scopeCurator=2;
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Apostles\BHA_Apostles_Ascended.jpg";
		Weapons[]=
		{
			"MET_X300_Sniper",
			"MET_D200",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_X300_Sniper",
			"MET_D200",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_D200_Pistol_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_X300_Sniper_mag",
			"MET_D200_Pistol_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
	class BHA_Apostles_Immortal: BHA_Apostles_Base
	{
		displayName="Apostle Immortal";
		scope=2;
		scopeCurator=2;
		icon="iconManMG";
		backpack="MET_SentinelPackMG_Night_Black";
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Apostles\BHA_Apostles_Immortal.jpg";
		Weapons[]=
		{
			"MET_T20_AC",
			"MET_D200",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_T20_AC",
			"MET_D200",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_T20AC_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_T20AC_mag",
			"MET_T20AC_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
	class BHA_Apostles_Diviner: BHA_Apostles_Base
	{
		displayName="Apostle Diviner";
		scope=2;
		scopeCurator=2;
		icon="iconManMedic";
		backpack="MET_SentinelPackMED_Night_Black";
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Apostles\BHA_Apostles_Diviner.jpg";
		Weapons[]=
		{
			"MET_T20_rifle",
			"MET_D200_Pistol_mag",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_T20_rifle",
			"MET_D200_Pistol_mag",
			"Put",
			"Throw"
		};
	};
	class BHA_Apostles_Annihilator: BHA_Apostles_Base
	{
		displayName="Apostle Annihilator";
		scope=2;
		scopeCurator=2;
		backpack="MET_SentinelPackGMG_Night_Black";
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Apostles\BHA_Apostles_Decimator.jpg";
		Weapons[]=
		{
			"MET_E403",
			"MET_D200",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_E403",
			"MET_D200",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_heavy_proton_mag",
			"MET_heavy_proton_mag",
			"MET_heavy_proton_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AA_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_heavy_proton_mag",
			"MET_heavy_proton_mag",
			"MET_heavy_proton_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
	class BHA_Apostles_Decimator: BHA_Apostles_Base
	{
		displayName="Apostle Decimator";
		scope=2;
		scopeCurator=2;
		icon="iconManAT";
		backpack="MET_SentinelPackAT_Night_Black";
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Apostles\BHA_Apostles_Decimator.jpg";
		Weapons[]=
		{
			"MET_T20_rifle",
			"MET_HH12_SMRT",
			"MET_D200",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_T20_rifle",
			"MET_HH12_SMRT",
			"MET_D200",
			"Put",
			"Throw"
		};
		Magazines[]=
		{
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AA_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
		respawnMagazines[]=
		{
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_T20_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"MET_D200_Pistol_mag",
			"BHA_AT_Single",
			"BHA_AT_Single",
			"BHA_AP_SINGLE",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Smoke_Black",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator"
		};
	};
	class BHA_Apostles_Archbishop: BHA_Apostles_Base
	{
		displayName="Apostle Archbishop";
		scope=2;
		scopeCurator=2;
		icon="iconManLeader";
		//editorPreview="\HDC_Units_mod\data\Editor Previews\BHA\Apostles\BHA_Apostles_Archbishop.jpg";
		Weapons[]=
		{
			"MET_T20_rifle",
			"MET_D200",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"MET_T20_rifle",
			"MET_D200",
			"Put",
			"Throw"
		};
	};
};
class CfgGroups
{
	class INDEP
	{
		class BHA_Groups
		{
			name="[16th] Barysaw Holdings Authority";
			class BHA_Apostles_inf_Groups
			{
				name="Apostle Infantry Groups";
				class BHA_Apostles_Squad
				{
					name="Squad";
					scope=2;
					side=2;
					faction="BHA_Units";
					icon="\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Unit0
					{
						side=2;
						vehicle="BHA_Apostles_Archbishop";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=2;
						vehicle="BHA_Apostles_Ascended";
						rank="PRIVATE";
						position[]={1,-2,0};
					};
					class Unit2
					{
						side=2;
						vehicle="BHA_Apostles_Immortal";
						rank="CORPORAL";
						position[]={-1,-2,0};
					};
					class Unit3
					{
						side=2;
						vehicle="BHA_Apostles_Diviner";
						rank="CORPORAL";
						position[]={1,-3,0};
					};
					class Unit4
					{
						side=2;
						vehicle="BHA_Apostles_Decimator";
						rank="CORPORAL";
						position[]={-1,-3,0};
					};
					class Unit5
					{
						side=2;
						vehicle="BHA_Apostles_Apostle";
						rank="CORPORAL";
						position[]={1,-4,0};
					};
					class Unit6
					{
						side=2;
						vehicle="BHA_Apostles_Annihilator";
						rank="CORPORAL";
						position[]={-1,-4,0};
					};
				};
			};
		};
	};
};
class cfgMods
{
	author="";
	timepacked="1664364859";
};
